apiVersion: v1
kind: Service
metadata:
  name: email-server-service
  namespace: final-year-project
spec:
  selector:
    app: email-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
