apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-server
  namespace: final-year-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-server
  template:
    metadata:
      labels:
        app: email-server
    spec:
      containers:
        - name: email-server
          image: 010123070122/email-server:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: email-env
